apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-frontend
  labels:
    app: tts-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-frontend
  template:
    metadata:
      labels:
        app: tts-frontend
    spec:
      containers:
        - name: tts-frontend
          image: liyf/tts-frontend:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
